language: java
jdk: oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HanDH4++PAWnxEnd6eYE37aN2MqcdTy6u03IDxFsjN8bL6QDQ7bgv6HLsjFXiFsI4+u3zwo8Lr1MVkwZhPkbvM0lohx/aOkMAAwzYLvefBH3Gpxg79U76gSTx2eOtZtnxLLP++czAvyagJshYgEIm2u7414JF9WUNsqzGmZHMZNwrO8Fdxrxza7L3De4zJhS46gy+BJFyeYCg3ET9GRxi11pinoBf73yecxBRv8sT66WcU7e5vfpRDxCay2qXOGuiR7U2th0KS1+TmWDHNxvtviYcq3XJswBUnH66qZK86hBuuY4T5dvGbwYoon7dAIwIMjWMhJgKOkTr6Q+GNA/RkxKWv1G4jXsKh1Jh7+3xTi6PgaEBfBzMq9sZPnZujAdSAwywsV9m8WoRV8MtAkxE5ZvbXOQfHZ6gU2eRt0TCLrAzM6tMfpDv7ma9McU7tAv1NEHwTcJNetiYVllplOtXgPqJ1kD1q2hsq9Z4txDB7fk4izXLThfZ/hMi7D8VxA25nnRp/9nH3vKxkgjdadiaGiEzPHWPdDgO5J2K4V8/FGPFPWLUcGN8zbajffevH0o5KOaZoX0G5RN/ABJEX3/ItgdRpi0a9v14/wnONWS8xix4aKdCk3Fgt22os7cnxCNP3bbbuC016e88CXXtlaHDXpGvjiAL3q6rtqB2fCktYs="

addons:
  coverity_scan:
    project:
      name: "jbhatt-salesforce/Warden-Service"
      description: "Build submitted via Travis CI"
    notification_email: jbhatt@salesforce.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

before_script:
  - pip install --user codecov

after_success:
  - codecov
